include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    prefer_const_constructors: true
    prefer_final_fields: true
    avoid_print: true
    always_put_control_body_on_new_line: false
    avoid_catches_without_on_clauses: false
    always_declare_return_types: true
    always_use_package_imports: false
    prefer_relative_imports: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    use_build_context_synchronously: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    prefer_interpolation_to_compose_strings: true

dart_style: 

analyzer:
  exclude:
    - "**/*.g.dart"
